---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 192.168.33.11
      ansible_ssh_private_key_file: "/home/smm/.ssh/id_rsa.pem"
    jenkins-agent-01:
      ansible_host: 192.168.33.12
      ansible_ssh_private_key_file: "/home/smm/.ssh/id_rsa.pem"
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant


 